# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Software Developer
email: deyvidferrer02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  <strong>I am Deyvid Ferrer</strong>, a super simple<br />
  responsive site template freebie<br />
  crafted by <a href="http://html5up.net">HTML5 UP</a>
bio: >- # this means to ignore newlines until "baseurl:"
  <strong>I am Deyvid Ferrer</strong>, a super simple<br />
  responsive site template freebie<br />
  crafted by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: deyvidferrer
github_username:  deyvidferrer
instagram_username:  deyvidferrer
youtube_username:  deyvidferrer
linkedin_username:  deyvidferrer
facebook_username:  deyvidferrer
author: Deyvid Ferrer | html5up
address: Caballito - Buenos Aires - Argentina
mobile: (+54) 911 39484008

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
