# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Software Developer
email: deyvidferrer02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am <strong>Deyvid Ferrer</strong>, a<br />
  freelance developer & designer.<br />
  I'm available for remote work
bio_intro: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Deyvid (pronounced "David"),
  a software developer with over <strong>8 years of experiences</strong>.
  Currently building the <a href="https:www.kiiah.com">Backend at Kiiah</a>.
bio_descr: >- # this means to ignore newlines until "baseurl:"
  I've always been drawn to the overlap between design and development.
  My skills are broad: from ux to design, front end to back end development.
  I enjoy each aspect, and my work is something I do with lot of honesty and commitment.
  Over the past years I had the opportunity to drive and do hands-on work for some amazing
  Canadian startups.
what_i_do: >-
  <dl>
  <dt>Front-end</dt>
  <dd>CSS3, Javascript, ES6, React</dd>
  <dt>Back-end</dt>
  <dd>NodeJS, Ruby, APIs, SQL</dd>
  <dt>CMS</dt>
  <dd>Wordpress,Jekyll</dd>
  <dt>Apps</dt>
  <dd>Mobile, React Native</dd>
  <dt>Cloud</dt>
  <dd>AWS, Google, Heroku</dd>
  <dt>E-Commerce</dt>
  <dd>Woocommerce, Shopify, Magento</dd>
  <dt>Tools</dt>
  <dd>Git, Postman, Photoshop, Illustrator, Atom, AdobeXD, Sketch</dd>
  </dl>
twitter_username: deyvidferrer
github_username:  deyvidferrer
instagram_username:  deyvidferrer
youtube_username:  deyvidferrer
linkedin_username:  deyvid-ferrer-9607a245
facebook_username:  deyvidferrer
author: Deyvid Ferrer
address: Caballito - Buenos Aires - Argentina
mobile: (+54) 911 39484008

# Build settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deyvidferrer.me" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
